"""Create a six-zone instrument and demo from synthesized tones only.

No external recordings, sample libraries, plugins, or downloads are used.
Run: python scripts/generate_sampler_demo.py --output-dir Tracks/sampler-demo
"""
import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
from scipy.io import wavfile

from music_engine import ZoneSampler


def build_instrument(folder, sample_rate=44100):
    folder = Path(folder)
    folder.mkdir(parents=True, exist_ok=True)
    t = np.arange(sample_rate * 2, dtype=np.float64) / sample_rate
    zones = []
    for root, low, high in [(48, 0, 53), (60, 54, 65), (72, 66, 127)]:
        frequency = 440 * 2 ** ((root - 69) / 12)
        envelope = (1 - np.exp(-t / .008)) * np.exp(-t / .65)
        envelope[-441:] *= np.linspace(1, 0, 441)
        for layer, vello, velhi, overtone in [('soft', 1, 79, .08), ('bright', 80, 127, .3)]:
            signal = .5 * envelope * (np.sin(2 * np.pi * frequency * t)
                                      + overtone * np.sin(4 * np.pi * frequency * t))
            name = f'tone-{root}-{layer}.wav'
            wavfile.write(folder / name, sample_rate, signal.astype(np.float32))
            zones.append(dict(name=f'Tone {root} {layer}', root=root, keylo=low,
                              keyhi=high, vello=vello, velhi=velhi,
                              group='Synth tones', file=name))
    (folder / 'manifest.json').write_text(json.dumps(zones, indent=2) + '\n')
    provenance = {
        'source': 'Generated by generate_sampler_demo.py using sine waves and envelopes',
        'external_audio': False,
        'sample_rate': sample_rate,
        'files': {z['file']: hashlib.sha256((folder/z['file']).read_bytes()).hexdigest() for z in zones},
    }
    (folder / 'provenance.json').write_text(json.dumps(provenance, indent=2) + '\n')
    return zones


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-dir', type=Path, default=Path('Tracks/sampler-demo'))
    args = parser.parse_args()
    folder = args.output_dir / 'instrument'
    build_instrument(folder)
    sampler = ZoneSampler(str(folder), deterministic=True, stereo_output=True)
    events = []
    for i, note in enumerate([48, 55, 60, 64, 67, 72, 64, 60]):
        start = i * .75
        events += [(round(start * 44100), 'on', 0, note, 64 if i % 2 == 0 else 104),
                   (round((start + .6) * 44100), 'off', 0, note, 0)]
    audio = sampler.render(events, total_seconds=8)
    assert audio.shape == (2, 8*44100) and np.isfinite(audio).all()
    peak = float(np.max(np.abs(audio)))
    assert peak > 0
    # A demonstration export, not the album mastering process.
    audio *= min(1.0, .9 / peak)
    wavfile.write(args.output_dir / 'demo.wav', 44100, audio.T.astype(np.float32))
    print(f'Generated six source WAVs, manifest, provenance and {args.output_dir / "demo.wav"}')


if __name__ == '__main__':
    main()
